2023-04-02 19:39:37.516996: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
wandb: WARNING Tried to auto resume run with id si6sjv3x but id 36kufc1f is set.
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in /home/klg6z/work/TransformerXL/STR_XL/Training/wandb/run-20230402_193943-36kufc1f
wandb: Run `wandb offline` to turn off syncing.
wandb: Resuming run 1 250
wandb: ‚≠êÔ∏è View project at https://wandb.ai/kendragivens/StrXL
wandb: üöÄ View run at https://wandb.ai/kendragivens/StrXL/runs/36kufc1f
Namespace(gpus=[0], dataset_path=None, dataset_artifact='sirdavidludwig/nachusa-dna/nachusa-dna:latest', encoder_path=None, encoder_artifact='sirdavidludwig/dnabert-pretrain/dnabert-pretrain-64dim:latest', seed=1, mem_switched=False, max_files=205, block_size=250, max_set_len=1000, num_induce=64, embed_dim=128, num_layers=8, num_heads=8, mem_len=250, dropout_rate=0.01, num_seeds=1, use_layernorm=True, pre_layernorm=True, use_keras_mha=True, set_len=1000, batches_per_epoch=20, validation_batch_size=5, save_to='StrXL_1_250', batch_size=20, sub_batch_size=0, data_workers=1, run_eagerly=False, use_dynamic_memory=False, wandb_project='StrXL', wandb_name=None, wandb_group=None, wandb_mode='online', resume='36kufc1f', initial_epoch=0, epochs=5)
Restoring previous model...
Traceback (most recent call last):
  File "/home/klg6z/work/TransformerXL/STR_XL/Training/StrXL_Induced_Training.py", line 140, in <module>
    sys.exit(tfu.scripting.boot(main, sys.argv))
  File "/home/klg6z/.local/lib/python3.10/site-packages/tf_utilities/scripting.py", line 106, in boot
    return job(*args, **kwargs) or 0
  File "/home/klg6z/work/TransformerXL/STR_XL/Training/StrXL_Induced_Training.py", line 126, in main
    model_path = tfu.scripting.restore(config.save_to + ".h5").name
  File "/home/klg6z/.local/lib/python3.10/site-packages/tf_utilities/scripting.py", line 206, in restore
    return wandb.restore(name, run_path, replace, root)
  File "/home/klg6z/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3640, in restore
    raise ValueError(f"File {name} not found in {run_path or root}.")
ValueError: File StrXL_1_250.h5 not found in kendragivens/StrXL/36kufc1f.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run summary:
wandb:                      best_epoch 910
wandb:                   best_val_loss 1.5892
wandb:                           epoch 944
wandb:                            loss 1.77586
wandb:     sparse_categorical_accuracy 0.4725
wandb:                        val_loss 2.34467
wandb: val_sparse_categorical_accuracy 0.32
wandb: 
wandb: üöÄ View run 1 250 at: https://wandb.ai/kendragivens/StrXL/runs/36kufc1f
wandb: Synced 3 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230402_193943-36kufc1f/logs
